version: "3.8"

services:
  backend:
    build:
      context: ./webapp_backend      
      dockerfile: ../Dockerfile.backend 
    ports:
      - "5000:5000"
    volumes:
      - ./webapp_backend:/app
    environment:
      - FLASK_ENV=production

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend  
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    depends_on:
      - backend
