FROM nvidia/cuda:12.6.2-cudnn-runtime-ubuntu20.04


WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-pip \
    build-essential \
    python3-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY webapp_backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

EXPOSE 5000

CMD ["python", "webapp_ModelAPI.py"]
